# Generated by Django 4.2.4 on 2023-08-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("city_name", models.CharField(max_length=100)),
                ("weather_main", models.CharField(max_length=50)),
                ("weather_description", models.CharField(max_length=200)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=8)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=8)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weather_icon", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "weather_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.weatherdata",
                    ),
                ),
            ],
        ),
    ]
