# Generated by Django 4.2.4 on 2023-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_weatherdata_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="lon",
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
