# Generated by Django 4.2.4 on 2023-09-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_alter_weatherdata_lat_alter_weatherdata_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingRecommendations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "weather_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.weatherdata",
                    ),
                ),
            ],
        ),
    ]
