# Generated by Django 4.2.4 on 2023-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_clothingrecommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingrecommendations",
            name="description",
            field=models.JSONField(),
        ),
    ]
